import { Inter } from "next/font/google";
import "@/styles/reset.css"
import "@/styles/global.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={inter.className} lang="en">
      <body className=" container">{children}</body>
    </html>
  );
}
