import { Inter } from "next/font/google";
import "@/styles/reset.css"
import "@/styles/global.css"
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={inter.className} lang="en">
      <body className=" container">
        <Header/>
        <main>{children}</main>
        <Footer/>
        </body>
    </html>
  );
}
